COD_DOcumento
Código do Dcoocumento
@!DOC_DR+"-"+DOC_NUM+"/"+DOC_ANO

15
XXXXXXXXXXXXXXX

DOC_DR
Diretoria
@!GRP_DONOREG,2

2
XX

DOC_ANO
Ano do Documento


2
99

DOC_NUM
Sequencial do Registyrtro


6





@DOC_DR,%ld

aDATA_CAD

Datat de  de Cadstramento doDo Documento
d
REF_TIPO
Tipo de Dcoocumento


20
XXXXXXXXXXXXXXXXXXXX
tTAB_tab_tipoAAviso
carta
fax
memorando
Oficio
Telex
ƒREF_NUM
Numeoro de Referencia do Documento


20
XXXXXXXXXXXXXXXXXXXX


REF_DATA

Datat do Documento de Refenciarencia
?„„„„„„

ORG_ORI

Orgao de Origem do documento de Referência

50


Assunto

Assunto

50


COD_STAT

cóCódigo do Status

2
S†X
tTAB_STATP
T
S
OBSERVACAO
Resumo
Resumo do Conteúdo do Documento
t
REmetente
Remetendtes
Remetentes
tŒŒ35
Interesasados
Interessados
Intereessados
tŒŒŒŒ35
Historico
Historico do Tramite do Documento
Histórico do Tramoite do Documento
t
Ult_data

Data do último aAndamento
d
ULT_HORA

Hora do UltioÚltimo Andamento
h
ULT_DOCDCODSTAT

Status do UÚltimo Andamento

2
X
ttab_statULT_STATUS

@#mat_stat[@ult_codstat,1,2]

20
XXXXXXXXXXXXXXXXXXXX

ULT_ENC

UltimoÚltimo Encaminhante

40


ULT_DEST

UÚltimo Destinatário

40


ULT_AUTOR

@	ƒ…U

16


ULT_OBS


t5ŒŒŒ56
PAL_CHAVES
Palavras Chaves
Palavras Chaves
yt
USU_DONOREG
UUsuário Dono do Registro
@u

15
xxxxx†††††XXXXXXXXXXXXXXX

USU_GRP_DONOREG	Gripo dono do Rgeistro
@Ll

40
xxxx††††XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

g