Andamento
n„„„†„†
bƒƒƒƒ‡…
Documento
Código do Documento : 
c

t„ 
„
t
c„„„„„„„

t„ 
„
c

t„ 
ƒ‡……Orgao ão de Origem     :„‡……Assunto             :ƒƒƒ…………………………………………„……Status : 
c„-------------------„„„„‡…„ˆˆ†
bƒƒƒƒƒƒƒƒƒƒƒƒƒ‡…„
Último Andamento
…Data .... . : 
c„„„„„„ƒƒƒ
…………………………Hora : 
c
 ……Autor : 
c„„„„

t „ 
††††††††††††††
t 
††††††††††††††
t 
„††††††††††††††††††De ....... : 
cƒƒƒ
„†††††††††††††Para ..... : 
c
„†††††††††††††Status ... : 
c„ƒƒƒƒƒ

v†
t
t
t„„„ ƒ „ 
… - 
c

t„‡………Observações: „…
c„„„

tg